### ISSUE TITLE
報修時傳送影像檔出現錯誤

### ISSUE THREAD

**Issue by mtch3n** [MingtseChen/iLife#6]
報修時傳送影像檔出現錯誤

**Comment by mtch3n** [comment]
this issue causes by package version not update to newest version

**Comment by changta921** [comment]
沒有出現錯誤了...但是也沒顯示出照片啊??另外，物品名稱標示為必填，但是不填也不會警告...

**Comment by mtch3n** [comment]
在某一版之後驗證功能失效
會再行更改
