### ISSUE TITLE
交通車程式修改(20180908)

### ISSUE THREAD

**Issue by changta921** [MingtseChen/iLife#8]
剛剛貼了下星期一交通班次，但是使用者的部分沒有顯示出來，想看看在星期一12:30前是否不能預約。
另外，交通車的管理介面，預設的排序以班次時間的降冪方式條列。(雖然可以自行選擇項目排列)，每班次已預約人數也請顯示。
謝謝!!!

**Comment by mtch3n** [comment]
ok fixed
